image: node:latest

stages:
    - install
    - build
    - run

cache:
    paths:
        - frontend/node_modules/

installer:
    stage: install
    script:
        - cd frontend/
        - npm ci

builder:
    stage: build
    script: 
        - cd frontend/
        - ls
        - npm ci
        - npm run build

runner:
    stage: run
    script:
        - cd frontend/
        - npm run start
        # - node test.js