image: node:latest

stages:
    - install
    - build
    - run

installer:
    stage: install
    script:
        - cd frontend/
        - npm ci
    artifacts:
        paths:
            - node_modules/

builder:
    stage: build
    script: 
        - cd frontend/
        - npm run build
    artifacts:
        paths:
            - frontend/

runner:
    stage: run
    script:
        - cd frontend/
        - npm run start
        # - node test.js
    artifacts:
        paths:
            - node_modules/