image: node:latest

stages:
    - install
    - build
    - run
.dependencies_cache:
  cache:
    key:
      files:
        - frontend/package-lock.json
    paths:
      - frontend/node_modules/
    policy: pull

# cache:
#     paths:
#         - frontend/node_modules/

installer:
    stage: install
    script:
        - cd frontend/
        - npm ci
    extends:
        .dependencies_cache
    cache:
        policy: pull-push
    artifacts:
        expire_in: 1h
        paths:
            - frontend/node_modules

builder:
    stage: build
    script: 
        - cd frontend/
        # - npm ci
        - npm run build

runner:
    stage: run
    script:
        - cd frontend/
        # - npm ci
        # - npm run start
        # - node test.js
        - npm test