version: "3.7"

services:
  node:
    build: ./node
    container_name: node
    restart: always
    ports:
      - "80:80"
      - "443:443"

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment: 
      - APP_NAME=MyFlaskApp
    expose:
      - 8080